# dummy config map for demo use with "Bridge to Kubenernetes"
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  #
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
# Ingress for demo for "Bridge to Kubernetes"
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: red-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # adjust your hosts file to resolve mying.blub to the IP of your ingress
  - host: mying.blub  
    http:
      paths:
        - path: /      
          backend:
            serviceName: svca
            servicePort: 80
---
# first service in a chain of services. (svca calls svcb which calls svcc)
# Only svca is available via public IP (therefore type: LoadBalancer)
# For Bridge to Kubernetes this is not required (you use the ingress for B2K)
# Find the corresponding deployments in a separate file for simple apply/delete.
apiVersion: v1
kind: Service
metadata:
  name: svca
  labels:
    name: svca    
spec:
  selector:
    app: appa
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svcb
  labels:
    name: svcb
spec:
  selector:
    app: appb
  type: ClusterIP
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svcc
  labels:
    name: svcc    
spec:
  selector:
    app: appc
  type: ClusterIP
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
