# dummy config map for use with local process
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  #
  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: red-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mying.blub  
    http:
      paths:
        - path: /      
          backend:
            serviceName: svca
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svca
  labels:
    name: svca    
spec:
  selector:
    app: appa
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svcb
  labels:
    name: svcb
spec:
  selector:
    app: appb
  type: ClusterIP
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svcc
  labels:
    name: svcc    
spec:
  selector:
    app: appc
  type: ClusterIP
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
